### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by B4TT3RY** [astorks/ScriptablePluginEngine#21]
```
[17:14:45] [Thread-13/WARN]: Exception in thread "Thread-13" java.lang.NullPointerException
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator$$Lambda$134/0000000000000000.compare(Unknown Source)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparators$NullComparator.compare(Comparators.java:83)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator$$Lambda$2357/0000000000000000.compare(Unknown Source)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparator$$Lambda$2357/0000000000000000.compare(Unknown Source)
[17:14:45] [Thread-13/WARN]: 	at java.base/java.util.Comparators$NullComparator.compare(Comparators.java:83)
[17:14:45] [Thread-13/WARN]: 	at com.smc.version.MinecraftVersion.compareTo(MinecraftVersion.java:253)
[17:14:45] [Thread-13/WARN]: 	at com.smc.version.MinecraftVersion.isBefore(MinecraftVersion.java:283)
[17:14:45] [Thread-13/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain$versionCheck$1.invoke(ScriptablePluginMain.kt:102)
[17:14:45] [Thread-13/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain$versionCheck$1.invoke(ScriptablePluginMain.kt:14)
[17:14:45] [Thread-13/WARN]: 	at khttp.async$Companion$request$3.invoke(KHttp.kt:113)
[17:14:45] [Thread-13/WARN]: 	at khttp.async$Companion$request$3.invoke(KHttp.kt:72)
[17:14:45] [Thread-13/WARN]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
[17:14:52] [Server thread/WARN]: [ScriptableMC-Engine-JS] Scriptable plugin engine failed to start.
[17:14:52] [Server thread/WARN]: Error: C:\Users\Administrator\Desktop\kSpigotTest\scripts\lib\java\io\File
[17:14:52] [Server thread/WARN]: 	at org.graalvm.polyglot.Context.eval(Context.java:344)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.core.ScriptablePluginEngine.eval(ScriptablePluginEngine.kt:175)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.core.ScriptablePluginEngine.start$ScriptableMC_Engine_JS(ScriptablePluginEngine.kt:78)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain$loadScriptEngine$1.invoke(ScriptablePluginMain.kt:56)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain$loadScriptEngine$1.invoke(ScriptablePluginMain.kt:14)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain.patchClassLoader$ScriptableMC_Engine_JS(ScriptablePluginMain.kt:128)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain.loadScriptEngine(ScriptablePluginMain.kt:53)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain.loadScriptEngine$default(ScriptablePluginMain.kt:51)
[17:14:52] [Server thread/WARN]: 	at com.pixlfox.scriptablemc.ScriptablePluginMain.onEnable(ScriptablePluginMain.kt:28)
[17:14:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:14:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[17:14:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:14:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[17:14:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[17:14:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[17:14:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[17:14:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[17:14:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[17:14:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[17:14:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
Bukkit: Paper 1.12.2 1618 Build
ScriptableMC: 1.1.10

**Comment by astorks** [comment]
It should just be a warning, the version check is broken in the latest release.
I've fixed it in the dev branch that should be released Monday or Tuesday.

**Comment by B4TT3RY** [comment]
ok, but how can i fix this?
`Error: (Bukkit Folder)\scripts\lib\java\io\File`

![image](https://user-images.githubusercontent.com/12368101/74601348-8efc0980-50e0-11ea-9ca8-88e9c9e0cbcb.png)

**Comment by astorks** [comment]
you forgot the `.js` in your import it should be `import File from './lib/java/io/File.js'`

**Comment by B4TT3RY** [comment]
oh my god autocomplete 😂

**Comment by astorks** [comment]
I had the same issue with vs code too. haha

Also I'm not sure if .filter and .foreach will work since the listFiles is a java array and works a bit odd.
The vanilla javascript for loop should work though.
